#!/usr/bin/env python
import re, sys, os

def getcodes(inpath, outpath):
    inpath2 = os.path.join('/usr/share/X11/xkb/keycodes', inpath)
    data = open(inpath2, 'r').read()
    data = re.sub(r'(//|#).*', '', data)
    tmp = outpath + '.tmp'
    f = open(tmp, 'w')
    kc = dict()
    try:
        print >>f, '; Automatically generated by "xkb.py"'
        print >>f
        print >>f, '; Keycodes'
        for m in re.finditer(r'<([^>]*)>\s*=\s*(\d+)\s*;', data):
            i = int(m.group(2), 0)
            n = m.group(1)
            print >>f, '%d\t%s' % (i, n)
            kc[n] = i
        print >>f
        print >>f, '; Aliases'
        for m in re.finditer(r'alias\s*<([^>]*)>\s*=\s*<([^>]*)>\s*;', data):
            n1 = m.group(1)
            n2 = m.group(2)
            print >>f, '%d\t%s' % (kc[n2], n1)
            kc[n1] = kc[n2]
        f.close()
        os.rename(tmp, outpath)
    except:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

getcodes('evdev', 'evdev.txt')
    
