/* This file is automatically generated. */
#include "keytable.h"
static const char KEYCODE_LINUX_NAME_DATA[] =
    "\0'\0,\0;\0A\0B\0Backspace\0C\0Caps Lock\0D\0Delete\0E\0End\0Escape\0F\0F"
    "1\0F10\0F11\0F12\0F13\0F14\0F15\0F16\0F17\0F18\0F19\0F2\0F20\0F21\0F22\0F"
    "23\0F24\0F3\0F4\0F5\0F6\0F7\0F8\0F9\0G\0H\0Home\0I\0Insert\0J\0K\0KP *\0K"
    "P +\0KP -\0KP .\0KP /\0KP 0\0KP 1\0KP 2\0KP 3\0KP 4\0KP 5\0KP 6\0KP 7\0KP"
    " 8\0KP 9\0KP =\0KP Enter\0KP NumLock\0L\0Left\0Left Alt\0Left Control\0Le"
    "ft Shift\0Left Super\0M\0Menu\0N\0Non-US \\\0O\0P\0Page Down\0Page Up\0Pa"
    "use\0Q\0R\0Right\0Right Alt\0Right Control\0Right Shift\0Right Super\0S\0"
    "Scroll Lock\0Space\0SysReq/Attention\0T\0Tab\0U\0V\0W\0X\0Y\0Z\0[\0]\0`";
static const unsigned short KEYCODE_LINUX_NAME_OFFSET[] = {
    0,0,0,0,7,9,21,33,42,55,144,146,153,162,164,266,317,324,335,337,363,365,421,
    458,464,466,468,470,472,474,58,70,74,78,82,86,90,94,98,62,0,48,11,460,435,
    179,244,476,478,333,0,5,1,480,3,184,189,23,57,100,123,126,129,132,135,138,
    141,60,64,68,0,423,357,155,148,349,35,44,339,367,268,344,354,255,186,166,
    176,171,246,196,201,206,211,216,221,226,231,236,191,181,326,0,0,241,72,76,
    80,84,88,92,96,103,107,111,115,119,0,0,319,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,441,0,0,0,249,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,282,295,273,306,383,397,373,409
};
const char *keycode_linux_name(unsigned index) {
    unsigned offset;
    if (232 <= index)
        return 0;
    offset = KEYCODE_LINUX_NAME_OFFSET[index];
    if (offset == 0)
        return 0;
    return KEYCODE_LINUX_NAME_DATA + offset;
}
