/* This file is automatically generated. */
#include "keytable.h"
static const char KEYCODE_MACOS_RAWNAME_DATA[] =
    "\0ANSI_0\0ANSI_1\0ANSI_2\0ANSI_3\0ANSI_4\0ANSI_5\0ANSI_6\0ANSI_7\0ANSI_8"
    "\0ANSI_9\0ANSI_A\0ANSI_B\0ANSI_Backslash\0ANSI_C\0ANSI_Comma\0ANSI_D\0ANS"
    "I_E\0ANSI_Equal\0ANSI_F\0ANSI_G\0ANSI_Grave\0ANSI_H\0ANSI_I\0ANSI_J\0ANSI"
    "_K\0ANSI_Keypad0\0ANSI_Keypad1\0ANSI_Keypad2\0ANSI_Keypad3\0ANSI_Keypad4"
    "\0ANSI_Keypad5\0ANSI_Keypad6\0ANSI_Keypad7\0ANSI_Keypad8\0ANSI_Keypad9\0A"
    "NSI_KeypadClear\0ANSI_KeypadDecimal\0ANSI_KeypadDivide\0ANSI_KeypadEnter"
    "\0ANSI_KeypadEquals\0ANSI_KeypadMinus\0ANSI_KeypadMultiply\0ANSI_KeypadPl"
    "us\0ANSI_L\0ANSI_LeftBracket\0ANSI_M\0ANSI_Minus\0ANSI_N\0ANSI_O\0ANSI_P"
    "\0ANSI_Period\0ANSI_Q\0ANSI_Quote\0ANSI_R\0ANSI_RightBracket\0ANSI_S\0ANS"
    "I_Semicolon\0ANSI_Slash\0ANSI_T\0ANSI_U\0ANSI_V\0ANSI_W\0ANSI_X\0ANSI_Y\0"
    "ANSI_Z\0CapsLock\0DownArrow\0End\0Escape\0F1\0F10\0F11\0F12\0F13\0F14\0F1"
    "5\0F16\0F17\0F18\0F19\0F2\0F20\0F3\0F4\0F5\0F6\0F7\0F8\0F9\0ForwardDelete"
    "\0Function\0Help\0Home\0ISO_Section\0JIS_Eisu\0JIS_Kana\0JIS_KeypadComma"
    "\0JIS_Underscore\0JIS_Yen\0LeftArrow\0Mute\0PageDown\0PageUp\0Return\0Rig"
    "htArrow\0RightCommand\0RightControl\0RightOption\0RightShift\0Space\0Tab"
    "\0UpArrow\0VolumeDown\0VolumeUp";
static const unsigned short KEYCODE_MACOS_RAWNAME_OFFSET[] = {
    71,586,118,143,168,150,661,647,100,633,802,78,543,640,125,561,654,619,8,15,
    22,29,43,36,132,64,50,499,57,1,568,517,626,475,175,524,902,468,182,550,189,
    593,85,107,608,510,492,531,975,969,157,776,0,691,920,925,963,668,951,938,
    958,946,933,783,729,343,0,432,0,452,0,326,998,987,881,362,380,0,415,733,737,
    397,196,209,222,235,248,261,274,287,744,300,313,863,848,832,754,757,760,748,
    763,766,814,705,823,713,725,717,0,701,0,709,0,721,792,797,895,769,751,687,
    741,886,698,871,909,677,979
};
const char *keycode_macos_rawname(unsigned index) {
    unsigned offset;
    if (127 <= index)
        return 0;
    offset = KEYCODE_MACOS_RAWNAME_OFFSET[index];
    if (offset == 0)
        return 0;
    return KEYCODE_MACOS_RAWNAME_DATA + offset;
}
