/* This file is automatically generated. */
#include "keytable.h"
static const char KEYCODE_MACOS_NAME_DATA[] =
    "\0'\0,\0.\0;\0A\0B\0C\0Caps Lock\0D\0Delete\0Delete Forward\0E\0End\0Esca"
    "pe\0F\0F1\0F10\0F11\0F12\0F13\0F14\0F15\0F16\0F17\0F18\0F19\0F2\0F20\0F3"
    "\0F4\0F5\0F6\0F7\0F8\0F9\0G\0H\0Help\0Home\0I\0J\0K\0KP *\0KP +\0KP -\0KP"
    " /\0KP 0\0KP 1\0KP 2\0KP 3\0KP 4\0KP 5\0KP 6\0KP 7\0KP 8\0KP 9\0KP =\0KP "
    "Clear\0KP Decimal\0KP Enter\0L\0Left\0Left Command\0Left Control\0Left Op"
    "tion\0Left Shift\0M\0Mute\0N\0O\0P\0Page Down\0Page Up\0Q\0R\0Return\0Rig"
    "ht\0Right Command\0Right Control\0Right Option\0Right Shift\0S\0Space\0T"
    "\0Tab\0U\0V\0W\0X\0Y\0Z\0[\0\\\0]\0`";
static const unsigned short KEYCODE_MACOS_NAME_OFFSET[] = {
    0,0,0,0,9,11,13,25,49,62,135,137,149,151,153,259,315,322,324,326,346,348,
    416,424,430,432,434,436,438,440,65,77,81,85,89,93,97,101,105,69,0,55,27,426,
    418,168,228,442,446,444,0,7,1,448,3,5,173,15,64,107,114,117,120,123,126,129,
    132,67,71,75,0,0,0,0,144,338,34,51,328,357,261,333,343,0,170,155,165,160,
    250,180,185,190,195,200,205,210,215,220,175,0,0,0,0,225,79,83,87,91,95,99,
    103,110,0,0,0,0,0,139,0,0,0,0,0,0,0,0,0,317,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,350,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,230,0,
    0,0,239,0,0,0,279,304,292,266,377,404,391,363
};
const char *keycode_macos_name(unsigned index) {
    unsigned offset;
    if (232 <= index)
        return 0;
    offset = KEYCODE_MACOS_NAME_OFFSET[index];
    if (offset == 0)
        return 0;
    return KEYCODE_MACOS_NAME_DATA + offset;
}
